import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/react"
import { roboto_mono } from "@/app/fonts";
import "./globals.css";
import NavBar from "./navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto_mono.className} antialiased`}>
        <NavBar/>
        <div className="mx-auto px-10">
         {children}
        </div>
      </body>
    </html>
  );
}
